server:
  port: 8891
spring:
  application:
    name: hs-tool
redis:
  host:
    ip: 127.0.0.1
    port: 16378
mail:
  host: smtp.sina.com
  port: 25
  user: test_gfire
  pass: xujiao0923
  from: test_gfire@sina.com
  ssl: false
